/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dyninv_constants.h"

namespace com { namespace seafooler { namespace project {

const dyninvConstants g_dyninv_constants;

dyninvConstants::dyninvConstants() {
}

}}} // namespace

