/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dyninv_CONSTANTS_H
#define dyninv_CONSTANTS_H

#include "dyninv_types.h"

namespace com { namespace seafooler { namespace project {

class dyninvConstants {
 public:
  dyninvConstants();

};

extern const dyninvConstants g_dyninv_constants;

}}} // namespace

#endif
